name          'tobru-uhosting'
version       '0.1.0'
source        'https://github.com/tobru/puppet-uhosting'
author        'tobru'
license       'BSD-3-Clause'
summary       'Simple Webhosting made easy'
description   ''
project_page  'https://github.com/tobru/puppet-uhosting'

dependency 'puppetlabs/stdlib'
